### ISSUE TITLE
Define roadmap

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#1]
### Objective
Define how is going to be the roadmap for the library

---

### Description
The first step of this work will be analyze how big Bulma library is, how each component interacts with eachother and what kind of hierarchy is defined.
That information will be taken to design and create a group of epics in several package versions which will add new features for the user.

---

### Steps
- [x] Review each component in [Bulma](https://bulma.io/documentation/)
- [x] Split them in `Atoms`, `Molecules` and `Organisms`
- [x] Save a draft in a document to be refined
- [x] Create first version of epics/versions based on previous findings

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Final documents
- [Roadmap public document](https://docs.google.com/document/d/1kWX-dDTD-cQUeB_Vbu0K6xRvtHaSA38h76yQnhiCe9U/edit?usp=sharing)

**Comment by NicolasOmar** [comment]
Public document published. These version could be expanded into more or could be extended with more features/enhancements as the stories and researchs give new information
