### ISSUE TITLE
Publish first version in npm

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#10]
### Objective
Be able to publish the first version of reactive-bulma in npm and reach 0.0.1

---

### Description
After setting all the needed tools (and customizing them), the idea is to push a basic version with the given code to be updated in future versions

---

### Tasks
- [ ] Publish first version (0.0.0-development) in npm
- [ ] Commit and push a version with minimal changes (like a new atom-level component) with `fix` notation
- [ ] Check repository version is now 0.0.1 on both github and npm

---

### Tickets
| Relationship | Involved tickets |
| :--- | :---: |
| Is child from | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **#9**

---

### Technical notes
Have in mind the project can be used at local level with [npm link](https://docs.npmjs.com/cli/v8/commands/npm-link)
