### ISSUE TITLE
Deploy Storybook instance

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#12]
### Objective
Prepare and deploy a Storybook instance for the library to be visible for all users.

---

### Description
In order to test the deployed components and show its feature to the public (possibly getting feedback from them), the best and easiest way is creating a Storybook instance to be public and any user can be able to use it.

---

### Tasks
- [ ] Create an automated deploy on [Netifly](https://app.netlify.com/)
- [ ] Achieve to run storybook from build in `main` branch
- [ ] Add deployed url to `README.md`

---

### Tickets
| Relationship | Involved tickets |
| :--- | :---: |
| Is child from | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **#9 - #10**
| It blocks |  **none**

---

### Technical notes
None
