### ISSUE TITLE
Setup linter suite

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#13]
### Objective 
Implement several libraries related to pre-commit and pre-push review.

---

### Description 
In order to avoid simple but possible code errors (like non unsed variables, a failing build or broken unit tests), I will implement a set of libraries used to integrate them as previous (and mandatory) steps before commit or push code. 

---

### Tasks 
- Research 
  - [x] Study libraries related documentation and implementation
    - [x] [eslint](https://eslint.org/docs/latest/use/getting-started) or [tslint](https://palantir.github.io/tslint/)
    - [x] [Prettier](https://prettier.io/docs/en/integrating-with-linters.html)
    - [x] [lint-staged](https://www.npmjs.com/package/lint-staged)
    - [x] [Husky](https://typicode.github.io/husky/#/)
  - [x] Study custom implementation having in mind rollup, storybook and typescript environment
- Development
  - [x] Create a branch
  - [x] Install needed package depedencies
    - [x] `eslint` or `tslint`
    - [x] `Prettier`
    - [x] `lint-staged`
    - [x] `Husky`

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **#13** 
| It blocks |  **#15**

---

### Technical notes 
TBD

**Comment by NicolasOmar** [comment]
After reading [this article about tsLint deprecation](https://typescript-eslint.io/linting/troubleshooting/tslint/), I will continue with es-lint and check its configuration setup having in mind the current setup

**Comment by NicolasOmar** [comment]
[This article](https://blog.logrocket.com/using-prettier-eslint-automate-formatting-fixing-javascript/) has been useful to integrate `prettier` and `es-lint`
