### ISSUE TITLE
Setup unit test suite

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#14]
### Objective 
Implement Jest test suit to implement unit tests on the project

---

### Description 
In order to review Reactive-bulma's codebase, I will have to implement Jest and integrate its first set of tests on the existing components with a minimun code coverage of 80%. 

---

### Tasks 
- Research 
  - [x] Study Jest related documentation and implementation on [its site](https://jestjs.io/docs/getting-started) 
  - [x] Study custom implementation having in mind rollup, storybook and typescript environment
- Development
  - [x] Create a branch
  - [x] Install needed package depedencies related to Jest (that could make it work on the mentioned codebase)
  - [x] Implement unit tests cases on the created components until achieve at least 80% of code coverage

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **#12** 
| It blocks |  **#13 - #15**

---

### Technical notes 
TBD
