### ISSUE TITLE
Improve component typing and comments

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#143]
### Objective 
Add new property for CSS classes and comments based on Typescript documentation.

---

### Description 
After reviewing some possible new components structure and actual types capabilities, I believe is a good moment to improve basic types with new properties like a `test-id` for container and child scopes, as well as include another for custom CSS classes that will bring extensibility to any component (and extend it to this new structures to come).
Besides the new types, I will move storybook descriptions from `.json` files to Typescript comments on `type/` files, that will add more explanatory context for any user that check any component's property to see what is its usage or reason.

---

### Tasks 
  - [x] Add `cssClasses` type and implement in all created components.
  - [x] Add types for style, css classes and test id in case of container (optional types) and implement in all created components.
  - [x] Move control descriptions from `index.mocks.json` files to its according types.

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **none** 
| It blocks |  **none**

---

### Technical notes 
None
