### ISSUE TITLE
Create component "Column"

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#15]
### Objective 
Create bulma's component `Column` from scratch

---

### Description 
Based on project's roadmap, this component will need to have the following specifications
- A code file based on React Hooks with Typescript
- A test file (`.test.tsx`) for its related unit tests
- A storybook file (`.stories.tsx`) to be deployed on a public Storybook site (and be tested for anyone)

---

### Tasks 
- Research 
  - [ ] Study its related documentation and implementation on [bulma's docs](https://bulma.io/documentation/columns/)
  - [ ] Document possible properties and behaviours
- Development 
  - [ ] Create its folder and a `index.tsx` file where the component will be coded
  - [ ] Create and/or update the needed interfaces, types, tuples and enums for the component
  - [ ] Create a `.test.ts` file for its units test and create the needed to reach at least 80% of code coverage
  - [ ] Create a `.stories.tsx` file for storybook stories and add at least 2 stories for different scenarios

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **#14** 
| It blocks |  **none**

---

### Technical notes 
None

**Comment by NicolasOmar** [comment]
Check coverage on SonarCloud settings to avoid files that are not `index.tsx` and `[component].tsx`
