### ISSUE TITLE
Extend Storybook "Docs" features

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#174]
### Objective
Add Storybook feature called `Description` to improve context understanding of each component.

---

### Description
After previous research related to Storybook features (see #47), I looked new possible ways to extend ReactiveBulma's documentation by add [Description](https://storybook.js.org/docs/react/api/doc-block-description) to each created and future component.

---

### Tasks
- Research
  - [x] Research about [Description](https://storybook.js.org/docs/react/api/doc-block-description) feature and any other needed to fullfil issue's objective.
- Development
  - [x] Implement the feature in all atom-level components
  - [x] Implement the feature in all molecule-level components

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **#47**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
None
