### ISSUE TITLE
Create an automated component template generator

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#180]
### Objective
Create a script to automate component templates.

---

### Description
In order to understand a more efficient way to manage component creation flow and reduce my time generating the same structure over and over, I will study [Hygen](https://www.npmjs.com/package/hygen) features and create a script which will setup a baseline for any component I will want to add to Reactive Bulma or future projects.

---

### Tasks
- Research
  - [x] Study [Hygen](https://www.npmjs.com/package/hygen)
  - [x] Look for examples or bibliography that provides examples of Hygen usage
- Development
  - [x] Install Hygen and set it up following the instructions
  - [x] Set up the new generator for a component, such tool should be capable of create a `.tsx`, a `stories.tsx`, a `test.tsx` and a `mock.json` file in a folder with linked boilerplate to be usabe even without adding more code.
  - [x] Add recommended usage as well as examples on documentation for future user's usage

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
None for now

**Comment by NicolasOmar** [comment]
First repo where I will look for [hygen usage](https://github.com/asermax/ui-library)
