### ISSUE TITLE
Integrate Codecov into project's workflow

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#19]
### Objective 
Implement Codecov to add a layer of unit test code coverage on project's CI/CD

---

### Description 
In order to achieve public-level test code coverage, I will have to implement Codecov in its CI/CD system (Github Actions) 

---

### Tasks 
- Research 
  - [x] Study Codecov related documentation and implementation on [its site](https://docs.codecov.com/docs/github-tutorial) 
  - [x] Define most effective way to apply it on Reactive-bulma's CI/CD pipelines (for PRs or Merge) 
- Development 
  - [ ] Make previous configurations regarding technology integration (tokens, account configs, etc)
  - [ ] Create a branch
  - [ ] Create or update the needed `.yml` file where the [Github Action](https://github.com/marketplace/actions/codecov) will be applied and apply its steps

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **none** 
| It blocks |  **none**

---

### Technical notes 
TBD
