### ISSUE TITLE
Reformulate roadmap's versions

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#20]
### Objective
Review original versions for the project, renew with a new set based on experienced changes and implement it on the needed places

---

### Description
Giving the unestable semantic-release implementation ( #9), the best way to avoid possible misunderstanding with future viewers is to check how versioning has been affected by semantic-release changes, what could be a more natural version set and make the needed changes on current references as well new ones as we see it necessary.

---

### Tasks
  - [x] Check original versioning proposal
  - [x] Check version changes caused for unstable npm publishing and semantic implementation
  - [x] Find possible patterns giving last changes using project's gitflow
  - [x] Make a new versioning proposal to be sustainable for future iterations
  - [x] Update versioning changes on [milestones](https://github.com/NicolasOmar/reactive-bulma/milestones)
  - [x] Update versioning changes on [project's description](https://github.com/users/NicolasOmar/projects/3?pane=info)
  - [x] Update versioning changes on [roadmap](https://docs.google.com/document/d/1kWX-dDTD-cQUeB_Vbu0K6xRvtHaSA38h76yQnhiCe9U)
  - [x] Add roadmap link to `README` file and check existing links are correct

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **#9**
| Is blocked by | **none**
| It blocks |  **none**
