### ISSUE TITLE
Integrate SonarCloud into project's workflow

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#23]
### Objective 
Implement SonarCloud to add a layer of code quality and vulnerabilities check on project's CI/CD

---

### Description 
In order to achieve public-level code quality and vulnerabilities analysis, I will have to implement SonarCloud in its CI/CD system (Github Actions) 

---

### Tasks 
- Research 
  - [x] Study SonarCloud related documentation and implementation on [its site](https://www.sonarsource.com/products/sonarcloud/) 
  - [x] Define most effective way to apply it on Reactive-bulma's CI/CD pipelines (for PRs or Merge) 
- Development 
  - [x] Make previous configurations regarding technology integration (tokens, account configs, etc)
  - [x] Create a branch
  - [x] Create or update the needed `.yml` file where the [Github Action](https://github.com/marketplace/actions/sonarcloud-scan) will be applied and apply its steps

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **none** 
| It blocks |  **none**

---

### Technical notes 
TBD
