### ISSUE TITLE
Add an automated issue uploader with github actions

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#258]
### Description
In order to maintain ReactiveBulma dependencies up to date (besides dependabot workflow) in a single update, I will create an Action to generate a new issue each week to make following in its CI/CD system (Github Actions)
  

---

### Tasks

- Research
  - [x] Study the issue creation flow by following [this related link](https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation)
  - [x] Define most effective way to apply it on Reactive-bulma's CI/CD pipelines (for PRs or Merge)
- Development
  - [x] Make previous configurations regarding technology integration (tokens, account configs, etc)
  - [x] Create a branch
  - [x] Create or update the needed `.yml` file 

---

### Ticket relationships

| Relationship | Involved tickets |
| :--- | :---: |
| Is related to | **none**
| Is blocked by | **none**
| It blocks | **none**  

---  

### Technical notes
TBD
