### ISSUE TITLE
Integrate Trivy into project's workflow

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#26]
### Objective 
Implement Trivy to add a layer of dependency vulnerabilities on project's CI/CD

---

### Description 
In order to achieve public-level dependency vulnerabilities analysis, I will have to implement Trivy in its CI/CD system (Github Actions) 

---

### Tasks 
- Research 
  - [x] Study Trivy related documentation and implementation on [its site](https://aquasecurity.github.io/trivy/v0.37/) 
  - [x] Define most effective way to apply it on Reactive-bulma's CI/CD pipelines (for PRs or Merge) 
- Development 
  - [x] Make previous configurations regarding technology integration (tokens, account configs, etc)
  - [x] Create a branch
  - [ ] Create or update the needed `.yml` file where the [Github Action](https://github.com/marketplace/actions/aqua-security-trivy) will be applied and apply its steps

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **none** 
| It blocks |  **none**

**Comment by NicolasOmar** [comment]
A point to have in mind after reading [language-specific packages documentation](https://aquasecurity.github.io/trivy/v0.20.2/vulnerability/detection/language/#fn:9) is that devDependencies of a package-lock.json files are not being included in trivy scans.

**Comment by NicolasOmar** [comment]
I created a [discussion](https://github.com/aquasecurity/trivy/discussions/3714) on Trivy's repository in order to know how possible is to scan development-level dependencies on a npm project or I should look for other type of solution

**Comment by NicolasOmar** [comment]
I created a [issue](https://github.com/aquasecurity/trivy/issues/3742) on trivy's repo to adress the problem rised on the discussion mentioned before. Hope this will go to somewhere

**Comment by NicolasOmar** [comment]
Closing issue because solution is not able to review development dependencies. I will work with another alternative in the near future.
