### ISSUE TITLE
Fix weekly update reminder

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#273]
### Description

To achieve complete integration with automated issue creator for weekly maintenance, I will have to include [add-to-project Action](https://github.com/actions/add-to-project/tree/main/) in its CI/CD system (Github Actions)

---
### Tasks

- Research
  - [x] Study `add-to-project` related documentation and implementation on <https://github.com/actions/add-to-project/tree/main/>
  - [x] Define the most effective way to apply it on Reactive-bulma's CI/CD pipelines (for PRs or Merge)

- Development
  - [x] Make previous configurations regarding technology integration (tokens, account configs, etc)
  - [x] Create a branch
  - [x] Create or update the needed `.yml` file where the `add-to-project` will be applied and apply its steps  

---

### Ticket relationships

| Relationship | Involved tickets |
| :--- | :---: |
| Is related to | **none**
| Is blocked by | **none**
| It blocks | **none**

---

### Technical notes

TBD
