### ISSUE TITLE
Learn about npm package workflow

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#3]
### Objective
Obtain information about npm publish workflow, having in mind its source code will be stored in GitHub (which has special integrations with npm) and work on a test project to find best practices for an automated npm package workflow.

---

### Description
Having in mind [semantic-release](https://semantic-release.gitbook.io/) complexity as well as releases in Github as well as Npm sites, the best option to have good results (using the proposd gitflow in #6), is to create a test repository with some basic code, deploy such repository in npm and github as well as integrating semantic release to automate releases giving branch version or any alternative achived during learning process.

---

### Tasks
- [x] Read needed npm related documentation
- [x] Read Github documentation related to npm integration
- [x] Create test repository
- [x] Create npm package and add needed data
- [x] Copy codebase from #5
- [x] Integrate semantic-relaese
- [x] Achieve a `patch release` in npm and github at same time (as `0.0.2`) with semantic-release
- [x] Achieve a `minor release` in npm and github at same time (as `0.1.0`) with semantic-release
- [x] Achieve a `major release` in npm and github at same time (as `2.0.0`) with semantic-release
- [x] Integrate [semantic-release Github Action](https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions) using a `.yml` file and default configuration
- [x] Achieve custom branching management on [semantic-release configuration](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration)
- [x] Achieve version sync between `package.json`, git release and npm version (see specific configuration for that)

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child from | **none**
| In parent of | **none**
| Is related to | **#5** - **#6**
| Is blocked by | **none**
| It blocks |  **#9**

---

### Technical notes
The used links on this investigations are the following:
- [Npm registry docs](https://docs.npmjs.com/about-the-public-npm-registry)
- [Working with GitHub and Npm](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry)
- [Semantic-release resources](https://semantic-release.gitbook.io/semantic-release/support/resources)
 - [[Video] First steps by Bayan Bennett](https://www.youtube.com/watch?v=vSxoV1KUF-A)
 - [[Video] Semantic-release by Bayan Bennett](https://www.youtube.com/watch?v=V3iggbCZi4E)
 - [[Video] Creating a npm package by James Q Quick ](https://www.youtube.com/watch?v=Knw8U5XyHaM)
 - [[Video] Creating a npm package by DesignCourse](https://www.youtube.com/watch?v=4zzbNac6f6Q)
 - [[Video] How to implement Semantic Release by Bruno Antunes](https://www.youtube.com/watch?v=QZdY4XYbqLI)
 - [[Video] Automate your GitHub Actions Releases by Dave's Dev Channel](https://www.youtube.com/watch?v=mah8PV6ugNY)

**Comment by NicolasOmar** [comment]
Undesrstand about npm accounts and organization accounts

**Comment by NicolasOmar** [comment]
The used code/repo/package is the following
- [Repository](https://github.com/NicolasOmar/test-npm-git-workflow)
- [Package](https://www.npmjs.com/package/@nicolasomar/npm-github-workflow-test)

**Comment by NicolasOmar** [comment]
After the needed research, I got to the conclusion that GitHub has a separated npm registry where you can publish your own packages on the same repository.
After researching the enough time, I decided to focus on npm only because the benefits (in my case) are none compared to have the package stored in main npm registry.

**Comment by NicolasOmar** [comment]
Starting to work on a custom gitflow-based config to use it in the main repository

**Comment by NicolasOmar** [comment]
After some tests related to the `.releaserc` configuration file. I am coming to the conclusion that could not be possible a strict implementation based on a static configuration rather than documenting a specific and methodic way to write commit/merge comments to structure version changes in the desired way.
Before closing the issue and get into definitive conclusions, I will write a new discussion on semantic-release channel to obtain certain guidence and a better understaing about the tool and its best practices.

**Comment by NicolasOmar** [comment]
I created a [new discussion](https://github.com/semantic-release/semantic-release/discussions/2698) to understand if my approach was not the correct one and if there is a correct way to achieve what I would like.

**Comment by NicolasOmar** [comment]
After some investigation regarding [semantic-release plugins](https://semantic-release.gitbook.io/semantic-release/usage/plugins) and the best way of implement them in a selective way to achieve update on `package.json`, `npm published version` and `Github Release version`

Documentation:
- [Semantic-release configuration](https://github.com/NicolasOmar/test-npm-git-workflow/blob/main/.releaserc)
- [Package.json](https://github.com/NicolasOmar/test-npm-git-workflow/blob/main/package.json)
- [GitHub Action used to deploy](https://github.com/NicolasOmar/test-npm-git-workflow/blob/main/.github/workflows/node.js.yml)

**Comment by NicolasOmar** [comment]
At this stage I will look at simplified gitflows to select a custom version which will fullfil my need for the project

- [Gitflow document](https://docs.google.com/document/d/13WD28JrMWBtfVToKcjgTNnS8OUoyknTluuowshJq6Dk/edit?usp=sharing)

**Comment by NicolasOmar** [comment]
To close the ticket, I want to add some final thoughts about the experience and the best practices regarding automated npm versioning:

- Before starting, check you have installed Node v18 or above because is a requirement from semantic.
- Log into npm on your local machine through cli with `npm login` and check you logged in with `npm whoami` (should return your username).
- Install `semantic-release` following the [steps provided by their tutorial](https://semantic-release.gitbook.io/semantic-release/usage/getting-started).
  - That should change your `package.json` file version to `0.0.0-development`. Leave it like that because you will not need to check it anymore.
- Install the following packages executing ` npm i --save-dev semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/release-notes-generator`.
- To publish your package for the first time, execute `npm publish --access public`.
	- It should be enough to have your first version publicly available on npm.
- Now, you should create a `.relaserc` file on your root folder and paste the content from [this file](https://github.com/NicolasOmar/test-npm-git-workflow/blob/v3.0.0/.releaserc).
  - The file is a configuration where `semantic-release` will only be used on the main branch as well as will use the list of plugins that will execute the following:
    - `commit-analyzer`: Analyze all commit history from the last release and generate a list to be exported.
    - `release-notes-generator`: Add a new release note for the next version to be published.
    - `changelog`: Create or update the CHANGELOG.md (like [this one](https://github.com/NicolasOmar/test-npm-git-workflow/blob/v3.0.0/CHANGELOG.md)) file with the previously formatted commits for the next version to be published.
    - `github`: Create a new git-tag and release for the package's repository. ([example](https://github.com/NicolasOmar/test-npm-git-workflow/releases))
    - `npm`: Create a new version for the package in its npm site. ([example](https://www.npmjs.com/package/@nicolasomar/npm-github-workflow-test?activeTab=versions))
    - `git`: Update the package.json version to the new one. ([example](https://github.com/NicolasOmar/test-npm-git-workflow/commit/cd5dad060295c409e809a3189c39b514ec8f80ae))
- Also, you should create a file to run the process mentioned above on GitHub Action (I used that CI) in a new set of folders (`.github` -> `workflow` -> `node.js.yml`) on your project's root and paste the content from [this file](https://github.com/NicolasOmar/test-npm-git-workflow/blob/v3.0.0/.github/workflows/node.js.yml)
  - The file should be in a location like this one `.github/workflows/node.js.yml`.

After executing the steps above, you should be able to commit the changes from your new files, commit them with a comment like `fix(): adding new files for automated version deploy process` and push in `main`.

That action will run the `semantic-release` process following the plugin list you provided, updating your Github release and tag, your published version on npm, and synchronizing the version number on your package.json file.

To understand which will be the gitflow I will implement, please go to [the related document](https://docs.google.com/document/d/13WD28JrMWBtfVToKcjgTNnS8OUoyknTluuowshJq6Dk).

Also above, there are the links of the used repository and package for these experiments.

**Comment by NicolasOmar** [comment]
Post-issue: Adding [another article to publish a npm package in a simplified way](https://blog.taskli.st/posts/how-to-publish-to-npm-in-2023)
