### ISSUE TITLE
Plan migration to Bulma v1.0

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#357]
### Objective

Analyze available updates of Bulma's version to 1.0.0 and generate a backlog for its integration.

---

### Description

After receiving the news about [Bulma's update to v1.0.0](https://bulma.io/documentation/start/migrating-to-v1/) and maintaining the library's dependencies up to date (having in mind some roadblocks like pending es-lint v9 migration), I think the best approach is to review what is new in this major version, seize any new change, give to each shape of an issue and work them as part of `v5.0.0` milestone.

---

### Tasks

- [x] Study [Bulma's update to v1.0.0](https://bulma.io/documentation/start/migrating-to-v1/).
- [x] List every change from the last version.
- [x] Order them by priority.
- [x] Generate the `v5.0.0` milestone with the sorted list of tasks as issues.

**Comment by NicolasOmar** [comment]
First notes from investigation:
- Installation is the same as before, including its [variation with SASS](https://bulma.io/documentation/customize/with-sass/)
- I might have to create a review issue for dark mode (after adjusting the refreshed components)
- Grid can be a separate component (having in mind its variants, such as smart and fixed)
- I will also need to update React to the latest version (to have a healthier ecosystem).

**Comment by NicolasOmar** [comment]
Closed due to this issue's objective has been completed, and now I will be focused on developing the component's migration
