### ISSUE TITLE
Learn about CI/CD tools

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#4]
### Objective
Investigate possible CI/CD tools potentials and tecnical factibility to be used on the library

---

### Description
Analyze how continuous integration and delivery (aka CD/CI) works on Github Action, how it can be implemented, which tools suit the best for this technical scenario and which are the best options,

---

### Tasks
- [x] Learn about options, documentation and implemention for:
  - [x] DAST/SAST
  - [x] Code quality
  - [x] Unit testing
  - [x] Semantic/automated release in npm
- [x] Look into GitHub Actions documentation and marketplace to understand more about possibilities

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child from | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
Possible tool options:
| Tool / Github Action | Type | Status | Will be implemented in version n°
| :--- | :---: | :---: | :---: |
| [Trivy](https://github.com/aquasecurity/trivy) / [GitHub Action](https://github.com/aquasecurity/trivy-action) | **DAST** | Approved | `0.1.0`
| [SonarCloud](https://www.sonarsource.com/products/sonarcloud/) / [GitHub Action](https://github.com/marketplace/actions/sonarcloud-scan) | **Code quality** | Approved | `0.1.0`
| [SonarCloud](https://www.sonarsource.com/products/sonarcloud/) / [GitHub Action](https://github.com/marketplace/actions/sonarcloud-scan) | **SAST** | Approved | `0.1.0`
| [Codecov](https://about.codecov.io/) / [GitHub Action](https://github.com/codecov/codecov-action) | **Unit tests** | Approved | `0.1.0`

**Comment by NicolasOmar** [comment]
For DAST tools, I will use Trivy, which good recommendations and a GitHub Action

**Comment by NicolasOmar** [comment]
The options finded for `DAST`, `SAST`, `Code quality` and `Unit testing coverage upload` have been updated on issue's description.
I will create the related issues for its implementation before starting `v0.1.0`
