### ISSUE TITLE
Study about component library documentation best practices

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#47]
### Objective 
Read about documentation examples related to component libraries to implement in Reactive-bulma

---

### Description 
Beyond implementation examples and documentation on code (something achivable with Typescript), a good idea is to review other libraries that have time beign implemented a good documentation, understand its strong points explaining its features, examples and contact (among other points), compare with reactive-bulma and improve its current documentations with the results obtained.

---

### Tasks 
- [x] Research about Storybook configuration to add documentation
- [x] Research about Typescript comments to improve documentation
- [x] Research on the provided bibliography in order to get ideas

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **none** 
| It blocks |  **none**

---

### Bibliography
- Style libraries (CSS/SASS/LESS only)
  - https://github.com/twbs/bootstrap
  - https://github.com/jgthms/bulma
  - https://github.com/tailwindlabs/tailwindcss
- Component libraries (style libraries with implemented on a JS library or framework)
  - https://github.com/fomantic/Fomantic-UI
  - https://github.com/mui/material-ui
  - https://github.com/ant-design/ant-design
- Articles:
  - https://medusajs.com/blog/how-we-improved-our-documentation/?utm_source=tldrnewsletter
  - https://dev.to/merlos/how-to-write-a-good-readme-bog
  - https://diataxis.fr/tutorials/
- Other to review:
  - Shields about issues and tracking process

**Comment by NicolasOmar** [comment]
Have in mind certain [Shields

**Comment by NicolasOmar** [comment]
Have in mine [Storybook arguments table](https://storybook.js.org/docs/react/writing-docs/doc-block-argstable) documentation to create the needed explanation of each component's properties and methods

**Comment by NicolasOmar** [comment]
Have also in mind [Typescript JSDoc Reference](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) to improve details of function implementation.
