### ISSUE TITLE
Change security integration by learning about Snyk

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#50]
### Objective 
Implement Snyk to add a layer of dependency vulnerabilities on project's CI/CD

---

### Description 
After investigating, implementing and having some near dead-end situation in #26 trying to implement Tryvi, I got some documentation related to Snyk, a tool which can make the same public-level dependency vulnerabilities analysis, I will have to implement it in its CI/CD system (Github Actions) 

---

### Tasks 
- Research 
  - [x] Study Snyk related documentation and implementation on [its site](https://docs.snyk.io) 
  - [x] Define most effective way to apply it on Reactive-bulma's CI/CD pipelines (for PRs or Merge) 
- Development 
  - [x] Make previous configurations regarding technology integration (tokens, account configs, etc)
  - [x] Create a branch
  - [x] Create or update the needed `.yml` file where the [Github Action](https://github.com/marketplace/actions/aqua-security-trivy) will be applied and apply its steps

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **#26** 
| Is blocked by | **none** 
| It blocks |  **none**
