### ISSUE TITLE
Input and other components needs name property to function in forms

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#511]
### Objective 
Add `name` property to all form input variations.

---

### Description 
After starting my migration from custom components to reactive-bulma-based, I checked that form-related inputs such as Input do not have the name property, which will produce several complications related to form data handling.

---

### Tasks 
  - [x] Update its `index.tsx` file where the component will be coded
  - [x] Create and/or update the needed interfaces, types, tuples and enums for the mentioned component
  - [x] Update its unit tests to reach at least 95% of code coverage
  - [x] In case of be needed update and/or add new storybook stories to show the new scenario/s

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **none** 
| It blocks |  **none**

---

### Technical notes 
None
