### ISSUE TITLE
FormField needs to be expanded

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#517]
### Objective 
FormField structure should be able to contain more types of inputs.

---

### Description 
After some iterations on my app's future version, I realized FormField should be able to include more possibilities, such as Checkboxes, Radio Buttons, and selectors, among others, to create forms with a more consistent design.
However, I am still figuring out the solution. So, I will look into ways to find the solution and make it extendable so that this situation doesn't repeat in future cases.

---

### Tasks 
- Research 
  - [ ] Study its related documentation and implementation on [FormFiel](https://reactivebulma.netlify.app/?path=/docs/organisms-formfield--docs)
- Development 
  - [ ] Work on one or several solutions.
  - [ ] Update its `index.tsx` file where the component will be coded
  - [ ] Create and/or update the needed interfaces, types, tuples, and enums for the mentioned component
  - [ ] Update its unit tests to reach at least 95% of code coverage
  - [ ] In case of be needed to update and/or add new storybook stories to show the new scenario/s

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **none** 
| Is blocked by | **none** 
| It blocks |  **none**

---

### Technical notes 
None yet.
