### ISSUE TITLE
Work on project's Community Standards

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#79]
### Objective 
Read about Github's Community Standards to implement in Reactive-bulma.

---

### Description
After working on #47 and being focused on project's presentation, my next step is to improve future community feedback by adding needed steps related to [Open Source Standards related to community](https://opensource.guide/) as well as looking for implementation examples that will guide me to have the best possible approach.
The tasks mentioned below have been added due [project's current community status](https://github.com/NicolasOmar/reactive-bulma/community).

---

### Tasks
- [x] Reseach about Open Source Standards
- [x] Research about implementation examples in provided bibliography
- [x] Add a `Code of conduct file` based on founded evidence and examples
- [x] Add a `Contributing file` based on founded evidence and examples
- [x] Add a `Security policy file` based on founded evidence and examples
- [x] Add a `Issue template` based on founded evidence and examples
- [x] Add a `Pull request template` based on founded evidence and examples

---

### Ticket relationships 
| Relationship | Involved tickets | 
| :--- | :---: | 
| Is related to | **#47** 
| Is blocked by | **none** 
| It blocks |  **none**

---

### Bibliography
- Style libraries (CSS/SASS/LESS only)
  - https://github.com/twbs/bootstrap
  - https://github.com/jgthms/bulma
  - https://github.com/tailwindlabs/tailwindcss
- Component libraries (style libraries with implemented on a JS library or framework)
  - https://github.com/fomantic/Fomantic-UI
  - https://github.com/mui/material-ui
  - https://github.com/ant-design/ant-design
- Articles:
  - To be added

**Comment by NicolasOmar** [comment]
About the Contributing file. I got some impressive example to learn from them:
- [Bootstrap](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [Material UI](https://github.com/mui/material-ui/blob/master/CONTRIBUTING.md)

**Comment by NicolasOmar** [comment]
Following several articles (mostly from GitHub) related to:
- [Issue and pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)
- [Code of conduct understanding](https://www.contributor-covenant.org/)
- [Your code of conduct](https://opensource.guide/code-of-conduct/)
- [Guidelines for new contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
