### ISSUE TITLE
Integrate Semantic-release into project's workflow

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/reactive-bulma#9]
### Objective
Integrate all the tested features of semantic-release into project's structure

---

### Description
After the previous research (having in mind the steps of this [npm workflow investigation comment](https://github.com/NicolasOmar/reactive-bulma/issues/3#issuecomment-1416572444)), I will integrate the best build I tested on the test project on reactive-bulma in order to automate releases using a custom git-flow for this project.

---

### Tasks
- [ ] Check package for needed adaptations in order to integrate semantic-release
- [ ] Create a branch
- [ ] Install the additional npm packages for plugins
- [ ] Install semantic by following its steps
- [ ] Adjust its `.github/workflows/[fileName].yml` file to do the needed work.
- [ ] Add the configuration file

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **#3 - #10**
| It blocks |  **none**
